---
openapi: 3.0.0
info:
  title: Swagger Petstore
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/KOUPTCHINSKYNG/test/1.0.1
  description: SwaggerHub API Auto Mocking
- url: https://petstore.swagger.io/v2
tags:
- name: category
  description: Operations about category
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /category:
    get:
      tags:
      - category
      summary: Get all categories
      operationId: getAllCategories
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      tags:
      - category
      summary: Add a category pet to the store
      operationId: addCategory
      requestBody:
        $ref: '#/components/requestBodies/Category'
      responses:
        "200":
          description: Category added
        "405":
          description: Invalid input
  /category/{categoryId}:
    get:
      tags:
      - category
      summary: Find category by ID
      description: Returns a single category
      operationId: getCategoryById
      parameters:
      - name: categoryId
        in: path
        description: ID of category to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        "400":
          description: Invalid ID supplied
        "404":
          description: Category not found
    delete:
      tags:
      - category
      summary: Deletes a category
      operationId: delete category
      parameters:
      - name: categoryId
        in: path
        description: Category id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Success
        "400":
          description: Invalid ID supplied
        "404":
          description: Category not found
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: computer
  requestBodies:
    Category:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
